# Documentation of compose spec can be found at https://github.com/compose-spec/compose-spec
# [Manfred, 21apr2023]

# According to the compose spec we can specify the compose project name here. However, VS Code does
# not honor this as of 21 Apr 2023. Therefore there is a .env file at the root of this git repository
# in which the environment variable COMPOSE_PROJECT_NAME is defined as 'rimutec'. Once VS Code supports
# the top-level element 'name', the following can be used instead.
name: 'rimutec'
# [Manfred, 21apr2023]

services:
   # change the service name, the container name and the hostname for each dev container that connects
   # to the same virtual network. [Manfred, 29jul2022]
   oidc-example-dev:
      image: oidc-example-dev:0.1
      build: .
      container_name: oidc-example-dev
      hostname: oidc-example-dev.local
      working_dir: /work
      ports:
         - "30514:3000" # for the example service
         - "30515:3100" # for the react application
         # Using double quotes for port mapping to avoid YAML reading it as a number with a different base
         # e.g. "3333:22" would result in port numbers greater than 130000 which are clearly invalid.
         # Without double quotes YAML interprets it as a number based on 22. [Manfred, 24aug2022]
      environment:
         CLIENT_ID: example-service
         CLIENT_SECRET: Gvasb4IrsOq8B0s93UHHN6tXznkOxpK9
      volumes:
         - ..:/work
      command: bash -c "/work/.devcontainer/init.sh && sleep infinity"
      networks:
         rimutec:

   oidc-example-kc:
      image: rimutec/keycloak:0.1
      build:
         context: .
         dockerfile: Dockerfile.keycloak
      container_name: oidc-example-kc
      hostname: oidc-example-kc.local
      ports:
         - "30524:8080"
         - "30525:8443"
      environment:
         KC_HOSTNAME: localhost
         KC_HOSTNAME_STRICT: "false"
         KC_DB: postgres
         KC_DB_USERNAME: dba
         KC_DB_PASSWORD: password
         KC_DB_SCHEMA: public
         KC_DB_URL: jdbc:postgresql://oidc-example-kc-db.local:5432/
         KEYCLOAK_ADMIN: admin
         KEYCLOAK_ADMIN_PASSWORD: password
      entrypoint: /opt/keycloak/bin/kc.sh start-dev
      depends_on:
         - oidc-example-kc-db
      networks:
         rimutec:

   oidc-example-kc-db:
      image: postgres
      container_name: oidc-example-kc-db
      hostname: oidc-example-kc-db.local
      environment:
         POSTGRES_PASSWORD: password
         POSTGRES_USER: dba
      ports:
         - "30526:5432"
      networks:
         rimutec:

networks:
   rimutec:
